### ISSUE TITLE
Health survey: Put "Main reason for individual mandate" and "Individual mandate: beneficial or detrimental?" in text analysis

### ISSUE THREAD

**Issue by Rainett** [Understanding-Economics/Understanding-Economics.github.io#102]

**Comment by adilbhatia98** [comment]
need images

**Comment by Rainett** [comment]
[Question_Q06002_wordcloud_2g_.pdf](https://github.com/Understanding-Economics/Understanding-Economics.github.io/files/4512342/Question_Q06002_wordcloud_2g_.pdf)
[Question_Q06001_wordcloud_2g_.pdf](https://github.com/Understanding-Economics/Understanding-Economics.github.io/files/4512343/Question_Q06001_wordcloud_2g_.pdf)
