### ISSUE TITLE
Trade survey: Example display

### ISSUE THREAD

**Issue by Rainett** [Understanding-Economics/Understanding-Economics.github.io#110]
Put the example below the three boxes

Would be something like:

topic: Small case study / question: Click to display question below / group

Let us now consider the following simplified example of what happens economically when there is more trade in some goods. Take for instance the car industry and the laptop industry. (...)  Imagine now that the U.S. starts importing even more cars and producing less cars domestically. **_What will happen to_**:

Bubbles

Proportions of responses to (same as now)

**Comment by TheKeveloper** [comment]
Seems fixed: http://understandingeconomics.org/#/survey/trade_survey?topic=Case+Study&question=Q06015_en&group=edugroup

**Comment by Rainett** [comment]
delete the text below question box
