### ISSUE TITLE
Double Taxation question answer

### ISSUE THREAD

**Issue by TheKeveloper** [Understanding-Economics/Understanding-Economics.github.io#122]
This question answer is way too long. Can we change it to be just "It is mostly taxing assets that have not been taxed before during the life of the owner."

<img width="1238" alt="Screen Shot 2020-04-24 at 12 06 56 PM" src="https://user-images.githubusercontent.com/3794259/80238522-35561500-8624-11ea-8bb4-216cbf56238a.png">

**Comment by Rainett** [comment]
Yes!
