### ISSUE TITLE
Medicare/Medicaid wordclouds missing

### ISSUE THREAD

**Issue by TheKeveloper** [Understanding-Economics/Understanding-Economics.github.io#124]
These two questions are of the wordcloud type but do not have an associated image:

https://understanding-economics.github.io/#/survey/health_survey?topic=Knowledge+about+policy&question=dummy_medicaid

https://understanding-economics.github.io/#/survey/health_survey?topic=Knowledge+about+policy&question=dummy_medicare

I'm not really sure if they are even worth keeping because I can't imagine the wordcloud for this is particularly useful.

**Comment by Rainett** [comment]
For those questions, we used the text input to assess whether it was correct or not. Then generated the variables "dummy_medicaid" and "dummy_medicare" (0=uncorrect, 1= correct). I'll upload a new version of the dataset with labels. Do you think we can leave it like this (with the labels)? Maybe add a line somewhere to explain how we did?

**Comment by Rainett** [comment]
Something like: 
_Medicare_
Correct and incorrect answers were determined by text analysis. An answer is correct if it mentions the words "elderly", "old", "retire", "65", or "senior". It is incorrect if it does not mention any of those, or if it mentions the words "poor", "income", or "poverty". 
_Medicaid_
Correct and incorrect answers were determined by text analysis. An answer is correct if it mentions the words "poor", "income", or "poverty". It is incorrect if it does not mention any of those, or if it mentions the words "elderly", "old", "retire", "65", or "senior". 

Feel free to edit text

**Comment by adilbhatia98** [comment]
yup, we can do it that way
