### ISSUE TITLE
General: graph colors

### ISSUE THREAD

**Issue by Rainett** [Understanding-Economics/Understanding-Economics.github.io#127]
What about the new palette you were talking about @TheKeveloper? I liked it, maybe we could give a try and show it to Stefanie
I thought about it because the color for correct answer bothers me as it is not the same palette as the answers display, but changing it depends on the choice of the palette.

**Comment by TheKeveloper** [comment]
New color palette added! And I think it makes sense for the correct answer color to be different from the main green color. This way it stands out a bit more.
