### ISSUE TITLE
General: text sizes

### ISSUE THREAD

**Issue by Rainett** [Understanding-Economics/Understanding-Economics.github.io#128]
Open to discussion but I think it would be easier to read if: 
- The size of the main text is _a little_ too big and "Proportion of responses to xxx" and "By yyy" too --> Reduce it
- The size of the text in colored legend boxes could be increased a bit (not too much though, up to three lines of text is ok)

**Comment by TheKeveloper** [comment]
Text sizes for both are fixed!
