### ISSUE TITLE
General: no axis for randomization questions?

### ISSUE THREAD

**Issue by Rainett** [Understanding-Economics/Understanding-Economics.github.io#130]
Randomized questions have no x-axis, would it be possible to add one without messing everything up?
Ex: https://understanding-economics.github.io/#/survey/income_survey?topic=Tax+Change+Behavior&group=partygroup&question=Q06004_1_en

**Comment by TheKeveloper** [comment]
This was intentional. We can add it back in, I just think it looks uglier and I don't know that it adds much more information? 
<img width="895" alt="Screen Shot 2020-04-24 at 3 14 47 PM" src="https://user-images.githubusercontent.com/3794259/80253187-693e3400-863e-11ea-9ce8-43f27af75ac3.png">

**Comment by Rainett** [comment]
I totally agree with the fact that it looks uglier but here it is more of a scientific requirement
Also, is there an easy way to avoid the proportion on the graph? Maybe just delete it as it is already stated before

**Comment by TheKeveloper** [comment]
I'm not sure we need it though? Because it should be implied that the max is 100%, and you can scroll over each portion to tell the percentage. I deleted the proportion label

**Comment by Rainett** [comment]
Ok!
