### ISSUE TITLE
Question not included in data? : If an elderly person is in need of long-term care, which program(s) will pay for that?

### ISSUE THREAD

**Issue by adilbhatia98** [Understanding-Economics/Understanding-Economics.github.io#145]
label just says TO DO in the google spreadsheet.

**Comment by Rainett** [comment]
Actually, those are ok! Check the spreadsheet, I've changed the answers with the correct answer. The one that is still problematic is "Who pays for long-term care" (Q04005_en in the survey), where there 3 three goods answers so I am not sure about how to display it. I'll look at it tomorrow

**Comment by Rainett** [comment]
This is a multiple-choice question with three correct answers. What would be the best option to represent it? I thought 0, 1, 2, or all answers correct, but I hesitate to count responses where the person also answered a wrong answer. The reference variable is "Q04005_en". I look at it tomorrow.
