### ISSUE TITLE
Can we change answer from "approximately half" to "0.5"

### ISSUE THREAD

**Issue by TheKeveloper** [Understanding-Economics/Understanding-Economics.github.io#150]
This question has "approximately half" as the correct answer: https://understanding-economics.github.io/#/survey/trade_survey?topic=Knowledge+about+policy&question=Q04007_en&group=edugroup

However, we can't display this on the histogram, so can we just make the correct answer 0.5 instead?

**Comment by Rainett** [comment]
Yes, display the correct answer at 50% on the graph, you can leave approximately half or ~50% for the text

**Comment by Rainett** [comment]
By the way, don"t you think it is a little strange to have "By Education level
Correct Answer: An answer is considered correct if it mentions the words 'poor', 'income', or 'poverty'. An answer is incorrect if it does not mention any of those words, or if it mentions the words 'elderly', 'old', 'retire', '65', or 'senior'. Source: Medicaid.gov"? Could you delete the "Correct answer:" for those questions?
