### ISSUE TITLE
Change "Uncorrect" to "Incorrect"

### ISSUE THREAD

**Issue by TheKeveloper** [Understanding-Economics/Understanding-Economics.github.io#156]
The label in the Medicaid and Medicare questions for wrong answers is "Uncorrect." It should be "Incorrect." This requires a change in the original data csv. 

https://understanding-economics.github.io/#/survey/health_survey?topic=Knowledge+about+policy&question=dummy_medicaid&group=edugroup

**Comment by Rainett** [comment]
Oups sorry, I thought I had already corrected that. Done (check v5)
