### ISSUE TITLE
Delete "control" "you" and "gender" (as discusses before)

### ISSUE THREAD

**Issue by Rainett** [Understanding-Economics/Understanding-Economics.github.io#175]

**Comment by adilbhatia98** [comment]
Can you clarify please

**Comment by TheKeveloper** [comment]
I thought we decided to keep the labels? Because this makes it easier for users to clearly identify and think about the differences without having to read the entire text.

**Comment by Rainett** [comment]
Oh sorry, I thought we had agreed on deleting them, but maybe I missed the part when we decided to keep it in the end
