### ISSUE TITLE
Add link to the paper and the online slides

### ISSUE THREAD

**Issue by TheKeveloper** [Understanding-Economics/Understanding-Economics.github.io#30]

**Comment by TheKeveloper** [comment]
@Rainett when these are available, can you comment the links here?

**Comment by Rainett** [comment]
This is the link to the slides: https://scholar.harvard.edu/files/stantcheva/files/slides_understanding_econ_20191218.pdf
For the paper, I think we have to wait fro the submission

**Comment by Rainett** [comment]
It will be done in the home page too!
