### ISSUE TITLE
Add the wordclouds to the website

### ISSUE THREAD

**Issue by TheKeveloper** [Understanding-Economics/Understanding-Economics.github.io#33]

**Comment by Rainett** [comment]
Hi Kevin, I sent it to you by email earlier, did you get them?

**Comment by Rainett** [comment]
[Question_Q02004_wordcloud_2g_.pdf](https://github.com/Understanding-Economics/Understanding-Economics.github.io/files/4272394/Question_Q02004_wordcloud_2g_.pdf)
[Question_Q02003_wordcloud_2g_.pdf](https://github.com/Understanding-Economics/Understanding-Economics.github.io/files/4272395/Question_Q02003_wordcloud_2g_.pdf)
[Question_Q02002_wordcloud_2g_.pdf](https://github.com/Understanding-Economics/Understanding-Economics.github.io/files/4272396/Question_Q02002_wordcloud_2g_.pdf)

**Comment by TheKeveloper** [comment]
Ah, yes, got them, thanks!

**Comment by Rainett** [comment]
I just thought about something: the word clouds are for the general population, not by group. It is something you have to take into account when adding them to the options (on the contrary, the keyness graphs have are divided by groups -- not the same than the ones we usually display though)

**Comment by TheKeveloper** [comment]
I can just make sure not to display the groups portion when we know it is a keyness graph or wordcloud?

**Comment by Rainett** [comment]
Perfect for word clouds. Would it be possible to be able to change groups for the keyness though? Basically, reduce groups to "age", "party", "ideology", "social class" and "education" (even though they do not have the same definition as for other topic sections, but we add a note on this)

**Comment by TheKeveloper** [comment]
Yes, are those the groups available for every keyness graph?

**Comment by Rainett** [comment]
Yes they are!

**Comment by TheKeveloper** [comment]
Which surveys are the word clouds for again? Or is it for an aggregate?

**Comment by Rainett** [comment]
There are word clouds for each survey but they are not divided by group. Look at the google drive spreadsheet, it may help you :)
