### ISSUE TITLE
Add keyness graphs

### ISSUE THREAD

**Issue by TheKeveloper** [Understanding-Economics/Understanding-Economics.github.io#34]

**Comment by Rainett** [comment]
![keyness_income_2g_rich_poor](https://user-images.githubusercontent.com/55542591/75633049-c9c96b80-5bcf-11ea-8b4b-250405f48ea6.png)
![keyness_income_2g_college_educated](https://user-images.githubusercontent.com/55542591/75633050-ca620200-5bcf-11ea-83c7-3d80448df4ec.png)
![keyness_income_2g_young_1](https://user-images.githubusercontent.com/55542591/75633051-cafa9880-5bcf-11ea-9be6-7f29b9379dc1.png)
![keyness_income_2g_ideology](https://user-images.githubusercontent.com/55542591/75633052-cb932f00-5bcf-11ea-8ba9-4cb3d57dc13e.png)
![keyness_income_2g_affiliation](https://user-images.githubusercontent.com/55542591/75633053-ccc45c00-5bcf-11ea-8c69-38f33866e039.png)
