### ISSUE TITLE
New tab: General characteristics

### ISSUE THREAD

**Issue by Rainett** [Understanding-Economics/Understanding-Economics.github.io#53]
Create a tab where visitors can look at the distribution of respondents' characteristics. 
The first choice box should be respondents' characteristics (and not topic), naming it "by characteristics" (and not "by group")

Also, add a line in this choice box for "Views of government", that opens a second choice box where you can choose the group and call the second box "by group" (see "Pooled" tab in "Understanding Economics -- Variable and Question Descriptions" on google drive for the corresponding variables)

Plot distribution as simple histograms (with the order I indicated in the "Groups" tab)

**Comment by TheKeveloper** [comment]
@Rainett, the spreadsheet that we have is using the dummy variables. Is there a reason why we are using the dummy variables rather than the original responses?

**Comment by Rainett** [comment]
Which variables are you talking about?

**Comment by TheKeveloper** [comment]
@Rainett, all of the variables within the "Pooled" tab on the spreadsheet are prefixed with `dummy` which makes them a 0-1 variable, which I'm not sure is what we want.

**Comment by Rainett** [comment]
Good catch, I'll look at it in a hour or so

**Comment by Rainett** [comment]
I changed the variables (and titles) in the spreadsheet. Thank you
