### ISSUE TITLE
Center bubbles

### ISSUE THREAD

**Issue by Rainett** [Understanding-Economics/Understanding-Economics.github.io#61]
For tax change behaviors but also for policy knowledge
As much as possible, the number of bubbles should be the same on each line
ex: 
- if there are 5 bubbles: 3 on the first line, 2 on the second
- if there are 6 bubbles: 3 on one line, 3 on the other

**Comment by TheKeveloper** [comment]
We should discuss this. I'm worried that if the number of bubbles in each row is constantly changing, it will look weird to the user. And centering on the second line looks visually weird. Not sure the best way to handle this.

**Comment by Rainett** [comment]
Ok noted!
