### ISSUE TITLE
Putting "All" in a different color of knowledge questions

### ISSUE THREAD

**Issue by Rainett** [Understanding-Economics/Understanding-Economics.github.io#63]
Could be to keep if with a darker shade of grey (the one from the question, darker than what we have now), and let the other group bubbles in a lighter shade (i.e. the shade they have now)
We could also use color, but not sure since we already use one for the correct answer.
In any case, it doesn't need to be very outstanding, but only to perceive a difference

**Comment by TheKeveloper** [comment]
Changed to be ALL in caps and to underline All. Changing the color seems a bit jarring to me. Will deploy changes soon so let me know what you think.

**Comment by Rainett** [comment]
Caps seems sufficient, good idea
