### ISSUE TITLE
Change group variables

### ISSUE THREAD

**Issue by Rainett** [Understanding-Economics/Understanding-Economics.github.io#80]
The variables to use for groups are indicated in the google sheet (change variable in id by id2)

**Comment by Rainett** [comment]
And display in corresponding order

**Comment by TheKeveloper** [comment]
@Rainett, one small thing, right now the "econ" grouping has 0/1 instead of No/Yes. Could you change this in the CSVs?

**Comment by Rainett** [comment]
My mistake, the variable to use is "econgroup" and not "econ"
Thanks

**Comment by TheKeveloper** [comment]
@Rainett it seems like econgroup is already in there and is about whether the respondent self-identifies as knowledgeable or not. However, econ is about whether the respondent studied economics. Should we keep both? Or just get rid of econ?

**Comment by Rainett** [comment]
I rushed a bit answering sorry. I uploaded a new version of the csv files. I'll ask Stefanie if we keep both.
