### ISSUE TITLE
Treatment Arm Issue

### ISSUE THREAD

**Issue by adilbhatia98** [Understanding-Economics/Understanding-Economics.github.io#85]
We are not sure whether this is larger issue, but it appears that for the first question in 6.4 (Trade Section) of the Survey Questionnaire (As trade with other countries has increased, to what extent do you think the following groups have lost or gained from it? Please rate on a scale of 1 to 5, 1 being "lost a lot" and 5 "gained a lot".), the "CONTROL" and "ME" treatment arms answered the same question, according to the data. However, the Survey Questionnaire and "Variable and Question Descriptions" spreadsheet list these treatments under different question ids. Julia, can you please explain how this question was asked and how the data was recorded?

In the spreadsheet the question ids are Q06001_1_en through Q06001_5_en and Q06201_1/Q06201_2. However, Q06201_1/Q06201_2 do not exist in the data.

**Comment by Rainett** [comment]
Hi Adil, let me check with Bea who directly participated in designing the surveys. I feel like it's only a problem in the questionnaire, a mistake in copy-paste

**Comment by adilbhatia98** [comment]
Sounds good thank you!

Adil Bhatia

**Comment by Rainett** [comment]
For the other questions, I think I deleted them by mistake. I am uploading a new version of the data with the missing variables, tell me if it is ok now, from what I have checked it is the case
The only problem should be for Q06001_1_en

Thanks! 
Julia

**Comment by Rainett** [comment]
Problem solved, I updated a new version of the data of Drive

**Comment by adilbhatia98** [comment]
Great, I’ll check it out tonight!

Adil Bhatia
