### ISSUE TITLE
Proportion in top tax rate correct answer issue

### ISSUE THREAD

**Issue by TheKeveloper** [Understanding-Economics/Understanding-Economics.github.io#90]
Right now, it says that the correct answer for the proportion in the top tax rate is 65%, https://github.com/Understanding-Economics/Understanding-Economics.github.io/blob/react/src/config/fields.json#L170-L171.

I'm pretty sure this is wrong. Do we know what the right number is?

@Rainett

**Comment by Rainett** [comment]
The correct answer is 0.65%! (cf. the files I sent to Adil, I am sending them to you too). Thanks
